Merge upstream original (#2)
* Speed optimisations for Android (#505)

* Misc optimisations to android.

* Updates to README and fixes from comments

* Not testing RSA

* Remove async from getAllGenericPasswordServices (#464)

Removed async from getAllGenericPasswordServices to fix 
```
 ERROR  Could not get all keys. TypeError: ReactNativeKeychain.getAllGenericPasswordServices is not a function. (In 'ReactNativeKeychain.getAllGenericPasswordServices()', 'ReactNativeKeychain.getAllGenericPasswordServices' is undefined)
```

* Fix Flow type for Options to work with exact_by_default=true (#483)

* Fix Flow type for Options to work with exact_by_default=true

Fixes #482

* Fix Flow type tests

* Added support for macos (#490)

* added macos example project

* added support of macos

* added command to run macos

* updated readme

* fixed jsbundle script

* fixed null pointer in dict

* Bump React Native to 0.66 (#511)

* Bump version to 8.0.0

Co-authored-by: Björn Allvin <bjorn@allvin.com>
Co-authored-by: Greg Keys <gregkeys+github@gmail.com>
Co-authored-by: Ashoat Tevosyan <ashoat@gmail.com>
Co-authored-by: Dmitry Osipa <dmytro.osipa@aura.com>
Co-authored-by: Joel Arvidsson <joel@oblador.se>