Fix UnrecoverableKeyException crash in android 8 (#186)
I have catch this bug in android emulator in Nexus 6 API 27. It crashed because `keyStore.containsAlias(service)` were returned true, but `keyStore.getKey(service, null)` were crashed with exceptions:
```
java.security.UnrecoverableKeyException: Failed to obtain information about key
Caused by: android.security.KeyStoreException: Invalid key blob
at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreSecretKeyFromKeystore(AndroidKeyStoreProvider.java:283)
```